
INSERT INTO USERS (ID_USER, NAME, PASSWORD, TYPE) VALUES (default, 'Admin', 'admin123', '1');
INSERT INTO USERS (ID_USER, NAME, PASSWORD, TYPE) VALUES (default, 'Giaco', 'giaco123', '0');
INSERT INTO USERS (ID_USER, NAME, PASSWORD, TYPE) VALUES (default, 'María', 'maria123', '0');
INSERT INTO USERS (ID_USER, NAME, PASSWORD, TYPE) VALUES (default, 'Cris', 'cris123', '0');


INSERT INTO TICKETS (ID_TICKET, STATUS_TICKET, DATE_TICKET, TYPE_TICKET, USER_ID) VALUES (default, 'Finalizado', '2023-12-31', 'Teclado', '3');
INSERT INTO TICKETS (ID_TICKET, STATUS_TICKET, DATE_TICKET, TYPE_TICKET, USER_ID) VALUES (default, 'En curso', '2024-02-01', 'Ratón', '2');
INSERT INTO TICKETS (ID_TICKET, STATUS_TICKET, DATE_TICKET, TYPE_TICKET, USER_ID) VALUES (default, 'En curso', '2024-03-01','Pantalla', '4');
INSERT INTO TICKETS (ID_TICKET, STATUS_TICKET, DATE_TICKET, TYPE_TICKET, USER_ID) VALUES (default, 'Iniciado', '2024-04-01','Correo', '2');

